// Generated by https://quicktype.io

export interface JSONDataTech {
    technologies: Technology[];
    courses: Course[];
}

export interface JSONDataCourse {
    courses: Course[];
}

export interface Technology {
    _id:         string;
    name:        string;
    description: string;
    difficulty:  number;
    courses:     Course[];
}

export interface Course {
    _id:  string;
    code: string;
    name: string;
}

export interface ComponentProps {
    technologies:Technology[];
    reRender:Function;
}

export interface EditProps {
    technologies:Technology[];
    courses:Course[];
    reRender:Function;
}

export interface CourseProps {
    courses: Course[];
}

export interface LoadingOverlayProps {
    enabled:boolean;
    bgColor:string;
    spinnerColor:string;
}
